const a = {};
const b = {};
a.b = b;
b.a = a;

export default {
  undefined,
  number: 2,
  string: 'xxx',
  true: true,
  false: false,
  symbol: Symbol('a'),
  function: () => {},
  pos: Infinity,
  neg: -Infinity,
  null: null,
  NaN,
  emptyArray: [],
  array: [1, 2, 'a', null, 'x'],
  WeakMap: new WeakMap(),
  Date: new Date(),
  RegExp: /[A-Za-z0-9]+/gi,
  get x() { return 2; },
  set x(x) { return x; },
  circularObject: { a, b },
  biggerObject: {
    queryUrl: 'card_last/354',
    doc: [{
      event: 'card_last',
      _dob: 1480203771,
      _maxage: 10,
      data: {
        cards: [{
          _doc: 'card',
          _type: 'soccer:card:player_season_stats',
          _id: 1831196,
          _generated: 1480203646,
          _updated: 1480203646,
          _client_generated: 1480203654,
          phrase: 'Tony for America MG has been booked by Joao Batista de Arruda and receives a first yellow card.',
          stats: {
            yellow_cards: 2,
            yellowred_cards: 0,
            red_cards: 0,
          },
          match: {
            _id: 9212297,
            _dt: {
              _doc: 'time',
              time: '23:00',
              date: '26/11/16',
              tz: 'CET',
              tzoffset: 3600,
              uts: 1480197600,
            },
            _utid: 325,
            _sid: 1,
            roundname: {
              _doc: 'tableround',
              _id: 37,
              name: 37,
            },
            a2: 'br',
            teams: {
              home: {
                _doc: 'team',
                _id: 5328,
                uid: 1973,
                virtual: false,
                name: 'America MG',
                mediumname: 'America Mineiro MG',
                abbr: 'MIN',
                iscountry: false,
              },
              away: {
                _doc: 'team',
                _id: 987542,
                uid: 1959,
                virtual: false,
                name: 'Sport Recife',
                mediumname: 'Sport Recife PE',
                abbr: 'REC',
                iscountry: false,
              },
            },
            score: {
              home: 2,
              away: 2,
            },
            aggregate: null,
            periods: {
              p1: {
                home: 0,
                away: 1,
              },
            },
            penalty_shootout: null,
            status: {
              _doc: 'status',
              _id: 7,
              name: '2nd half',
            },
            periodlength: 45,
            numberofperiods: 2,
          },
          season: {
            _id: 12825,
            name: 'Brasileiro Serie A 2016',
            year: '2016',
            seasontype: '21',
            tournamentname: 'Brasileiro Serie A',
            roundbyround: true,
          },
          tournament: {
            _utid: 325,
            name: 'Brasileiro Serie A',
            roundbyround: true,
            seasontype: '21',
          },
          event: {
            _id: 269275536,
            _utid: 1973,
            type: 'card',
            time: 83,
            injurytime: 0,
            disabled: 0,
            name: 'Yellow card',
            card: 'yellow',
          },
          player: {
            _id: 243337,
            _utid: 1973,
            shirtnumber: 20,
            name: 'Tony',
            fullname: 'Carvalho, Antonio de Moura',
            position: {
              name: 'Midfielder',
            },
          },
        }, {
          _doc: 'card',
          _type: 'soccer:card:player_season_stats',
          _id: 1831164,
          _generated: 1480203568,
          _updated: 1480203568,
          _client_generated: 1480203599,
          phrase: 'Sport Recife\'s Matheus Ferraz has been booked in Belo Horizonte.',
          stats: {
            yellow_cards: 6,
            yellowred_cards: 1,
            red_cards: 0,
          },
          match: {
            _id: 9212297,
            _dt: {
              _doc: 'time',
              time: '23:00',
              date: '26/11/16',
              tz: 'CET',
              tzoffset: 3600,
              uts: 1480197600,
            },
            _utid: 325,
            _sid: 1,
            roundname: {
              _doc: 'tableround',
              _id: 37,
              name: 37,
            },
            a2: 'br',
            teams: {
              home: {
                _doc: 'team',
                _id: 5328,
                uid: 1973,
                virtual: false,
                name: 'America MG',
                mediumname: 'America Mineiro MG',
                abbr: 'MIN',
                iscountry: false,
              },
              away: {
                _doc: 'team',
                _id: 987542,
                uid: 1959,
                virtual: false,
                name: 'Sport Recife',
                mediumname: 'Sport Recife PE',
                abbr: 'REC',
                iscountry: false,
              },
            },
            score: {
              home: 2,
              away: 2,
            },
            aggregate: null,
            periods: {
              p1: {
                home: 0,
                away: 1,
              },
            },
            penalty_shootout: null,
            status: {
              _doc: 'status',
              _id: 7,
              name: '2nd half',
            },
            periodlength: 45,
            numberofperiods: 2,
          },
          season: {
            _id: 12825,
            name: 'Brasileiro Serie A 2016',
            year: '2016',
            seasontype: '21',
            tournamentname: 'Brasileiro Serie A',
            roundbyround: true,
          },
          tournament: {
            _utid: 325,
            name: 'Brasileiro Serie A',
            roundbyround: true,
            seasontype: '21',
          },
          event: {
            _id: 269275438,
            _utid: 1959,
            type: 'card',
            time: 81,
            injurytime: 0,
            disabled: 0,
            name: 'Yellow card',
            card: 'yellow',
          },
          player: {
            _id: 329083,
            _utid: 1959,
            shirtnumber: 16,
            name: 'Ferraz, Matheus',
            fullname: 'Ferraz Pereira, Matheus',
            position: {
              name: 'Defender',
            },
          },
        }, {
          _doc: 'card',
          _type: 'soccer:substitution',
          _id: 1831132,
          _generated: 1480203566,
          _updated: 1480203566,
          _client_generated: 1480203584,
          phrase: 'Ze Roberto (Ponte Preta) has replaced the possibly injured Ravanelli.',
          stats: [],
          match: {
            _id: 9212281,
            _dt: {
              _doc: 'time',
              time: '23:00',
              date: '26/11/16',
              tz: 'CET',
              tzoffset: 3600,
              uts: 1480197600,
            },
            _utid: 325,
            _sid: 1,
            roundname: {
              _doc: 'tableround',
              _id: 37,
              name: 37,
            },
            a2: 'br',
            teams: {
              home: {
                _doc: 'team',
                _id: 5903,
                uid: 1958,
                virtual: false,
                name: 'Botafogo RJ',
                mediumname: 'Botafogo RJ',
                abbr: 'BOT',
                iscountry: false,
              },
              away: {
                _doc: 'team',
                _id: 5332,
                uid: 1969,
                virtual: false,
                name: 'Ponte Preta',
                mediumname: 'Ponte Preta SP',
                abbr: 'PON',
                iscountry: false,
              },
            },
            score: {
              home: 1,
              away: 1,
            },
            aggregate: null,
            periods: {
              p1: {
                home: 1,
                away: 0,
              },
            },
            penalty_shootout: null,
            status: {
              _doc: 'status',
              _id: 7,
              name: '2nd half',
            },
            periodlength: 45,
            numberofperiods: 2,
          },
          season: {
            _id: 12825,
            name: 'Brasileiro Serie A 2016',
            year: '2016',
            seasontype: '21',
            tournamentname: 'Brasileiro Serie A',
            roundbyround: true,
          },
          tournament: {
            _utid: 325,
            name: 'Brasileiro Serie A',
            roundbyround: true,
            seasontype: '21',
          },
          event: {
            _id: 269275430,
            _utid: 1969,
            type: 'substitution',
            time: 81,
            injurytime: 0,
            disabled: 0,
            name: 'Substitution',
            playerin: {
              _doc: 'player',
              _id: 1049631,
              name: 'Roberto, Ze',
              fullname: 'Assuncao de Araujo Filho, Jose Roberto',
              birthdate: {
                _doc: 'time',
                time: '00:00',
                date: '14/09/93',
                tz: 'CEST',
                tzoffset: 7200,
                uts: 747957600,
              },
              nationality: {
                _doc: 'countrycode',
                _id: 30,
                a2: 'br',
                name: 'Brazil',
                a3: 'BRA',
                ioc: 'BRA',
                continentid: 3,
                continent: 'South America',
                population: 192900000,
              },
              position: {
                _type: 'F',
                name: 'Forward',
                shortname: 'STR',
                abbr: 'F',
              },
            },
            playerout: {
              _doc: 'player',
              _id: 881404,
              name: 'Ravanelli',
              fullname: 'Ferreira Dos Santos, Ravanelli',
              birthdate: {
                _doc: 'time',
                time: '00:00',
                date: '29/08/97',
                tz: 'CEST',
                tzoffset: 7200,
                uts: 872805600,
              },
              nationality: {
                _doc: 'countrycode',
                _id: 30,
                a2: 'br',
                name: 'Brazil',
                a3: 'BRA',
                ioc: 'BRA',
                continentid: 3,
                continent: 'South America',
                population: 192900000,
              },
              position: {
                _type: 'M',
                name: 'Midfielder',
                shortname: 'MID',
                abbr: 'M',
              },
            },
          },
        }, {
          _doc: 'card',
          _type: 'soccer:substitution',
          _id: 1831100,
          _generated: 1480203554,
          _updated: 1480203554,
          _client_generated: 1480203569,
          phrase: 'Vinicius Tanque is replacing Airton for Botafogo RJ at Estadio Luso Brasileiro.',
          stats: [],
          match: {
            _id: 9212281,
            _dt: {
              _doc: 'time',
              time: '23:00',
              date: '26/11/16',
              tz: 'CET',
              tzoffset: 3600,
              uts: 1480197600,
            },
            _utid: 325,
            _sid: 1,
            roundname: {
              _doc: 'tableround',
              _id: 37,
              name: 37,
            },
            a2: 'br',
            teams: {
              home: {
                _doc: 'team',
                _id: 5903,
                uid: 1958,
                virtual: false,
                name: 'Botafogo RJ',
                mediumname: 'Botafogo RJ',
                abbr: 'BOT',
                iscountry: false,
              },
              away: {
                _doc: 'team',
                _id: 5332,
                uid: 1969,
                virtual: false,
                name: 'Ponte Preta',
                mediumname: 'Ponte Preta SP',
                abbr: 'PON',
                iscountry: false,
              },
            },
            score: {
              home: 1,
              away: 1,
            },
            aggregate: null,
            periods: {
              p1: {
                home: 1,
                away: 0,
              },
            },
            penalty_shootout: null,
            status: {
              _doc: 'status',
              _id: 7,
              name: '2nd half',
            },
            periodlength: 45,
            numberofperiods: 2,
          },
          season: {
            _id: 12825,
            name: 'Brasileiro Serie A 2016',
            year: '2016',
            seasontype: '21',
            tournamentname: 'Brasileiro Serie A',
            roundbyround: true,
          },
          tournament: {
            _utid: 325,
            name: 'Brasileiro Serie A',
            roundbyround: true,
            seasontype: '21',
          },
          event: {
            _id: 269275410,
            _utid: 1958,
            type: 'substitution',
            time: 81,
            injurytime: 0,
            disabled: 0,
            name: 'Substitution',
            playerin: {
              _doc: 'player',
              _id: 558154,
              name: 'Vinicius Tanque',
              fullname: 'de Souza Oliveira, Vinicius Rodolfo',
              birthdate: {
                _doc: 'time',
                time: '00:00',
                date: '27/03/95',
                tz: 'CEST',
                tzoffset: 7200,
                uts: 796255200,
              },
              nationality: {
                _doc: 'countrycode',
                _id: 30,
                a2: 'br',
                name: 'Brazil',
                a3: 'BRA',
                ioc: 'BRA',
                continentid: 3,
                continent: 'South America',
                population: 192900000,
              },
              position: {
                _type: 'M',
                name: 'Midfielder',
                shortname: 'MID',
                abbr: 'M',
              },
            },
            playerout: {
              _doc: 'player',
              _id: 36685,
              name: 'Airton',
              fullname: 'Ribeiro Santos, Airton',
              birthdate: {
                _doc: 'time',
                time: '00:00',
                date: '21/02/90',
                tz: 'CET',
                tzoffset: 3600,
                uts: 635554800,
              },
              nationality: {
                _doc: 'countrycode',
                _id: 30,
                a2: 'br',
                name: 'Brazil',
                a3: 'BRA',
                ioc: 'BRA',
                continentid: 3,
                continent: 'South America',
                population: 192900000,
              },
              position: {
                _type: 'M',
                name: 'Midfielder',
                shortname: 'MID',
                abbr: 'M',
              },
            },
          },
        }, {
          _doc: 'card',
          _type: 'soccer:substitution',
          _id: 1831068,
          _generated: 1480203546,
          _updated: 1480203546,
          _client_generated: 1480203554,
          phrase: 'The home team replace Neilton with Gervasio Nunez.',
          stats: [],
          match: {
            _id: 9212281,
            _dt: {
              _doc: 'time',
              time: '23:00',
              date: '26/11/16',
              tz: 'CET',
              tzoffset: 3600,
              uts: 1480197600,
            },
            _utid: 325,
            _sid: 1,
            roundname: {
              _doc: 'tableround',
              _id: 37,
              name: 37,
            },
            a2: 'br',
            teams: {
              home: {
                _doc: 'team',
                _id: 5903,
                uid: 1958,
                virtual: false,
                name: 'Botafogo RJ',
                mediumname: 'Botafogo RJ',
                abbr: 'BOT',
                iscountry: false,
              },
              away: {
                _doc: 'team',
                _id: 5332,
                uid: 1969,
                virtual: false,
                name: 'Ponte Preta',
                mediumname: 'Ponte Preta SP',
                abbr: 'PON',
                iscountry: false,
              },
            },
            score: {
              home: 1,
              away: 1,
            },
            aggregate: null,
            periods: {
              p1: {
                home: 1,
                away: 0,
              },
            },
            penalty_shootout: null,
            status: {
              _doc: 'status',
              _id: 7,
              name: '2nd half',
            },
            periodlength: 45,
            numberofperiods: 2,
          },
          season: {
            _id: 12825,
            name: 'Brasileiro Serie A 2016',
            year: '2016',
            seasontype: '21',
            tournamentname: 'Brasileiro Serie A',
            roundbyround: true,
          },
          tournament: {
            _utid: 325,
            name: 'Brasileiro Serie A',
            roundbyround: true,
            seasontype: '21',
          },
          event: {
            _id: 269275394,
            _utid: 1958,
            type: 'substitution',
            time: 81,
            injurytime: 0,
            disabled: 0,
            name: 'Substitution',
            playerin: {
              _doc: 'player',
              _id: 157127,
              name: 'Nunez, Gervasio',
              fullname: 'Nunez, Gervasio Daniel',
              birthdate: {
                _doc: 'time',
                time: '00:00',
                date: '29/01/88',
                tz: 'CET',
                tzoffset: 3600,
                uts: 570409200,
              },
              nationality: {
                _doc: 'countrycode',
                _id: 10,
                a2: 'ar',
                name: 'Argentina',
                a3: 'ARG',
                ioc: 'ARG',
                continentid: 3,
                continent: 'South America',
                population: 40100000,
              },
              position: {
                _type: 'M',
                name: 'Midfielder',
                shortname: 'MID',
                abbr: 'M',
              },
            },
            playerout: {
              _doc: 'player',
              _id: 329223,
              name: 'Neilton',
              fullname: 'Meira Mestzk, Neilton',
              birthdate: {
                _doc: 'time',
                time: '00:00',
                date: '17/02/94',
                tz: 'CET',
                tzoffset: 3600,
                uts: 761439600,
              },
              nationality: {
                _doc: 'countrycode',
                _id: 30,
                a2: 'br',
                name: 'Brazil',
                a3: 'BRA',
                ioc: 'BRA',
                continentid: 3,
                continent: 'South America',
                population: 192900000,
              },
              position: {
                _type: 'F',
                name: 'Forward',
                shortname: 'STR',
                abbr: 'F',
              },
            },
          },
        }, {
          _doc: 'card',
          _type: 'soccer:goal:player_season_stats_dc',
          _id: 1831036,
          _generated: 1480203518,
          _updated: 1480203520,
          _client_generated: 1480203539,
          phrase: 'Goal! Ronaldo Alves (Sport Recife) levels the score at 2-2 with a header in Belo Horizonte.',
          stats: {
            assists: 0,
            minutes_per_goal: 1694,
            goals: 1,
            goals_by_header: 1,
            win_probability: {
              home: 6,
              draw: 63,
              away: 31,
            },
          },
          match: {
            _id: 9212297,
            _dt: {
              _doc: 'time',
              time: '23:00',
              date: '26/11/16',
              tz: 'CET',
              tzoffset: 3600,
              uts: 1480197600,
            },
            _utid: 325,
            _sid: 1,
            roundname: {
              _doc: 'tableround',
              _id: 37,
              name: 37,
            },
            a2: 'br',
            teams: {
              home: {
                _doc: 'team',
                _id: 5328,
                uid: 1973,
                virtual: false,
                name: 'America MG',
                mediumname: 'America Mineiro MG',
                abbr: 'MIN',
                iscountry: false,
              },
              away: {
                _doc: 'team',
                _id: 987542,
                uid: 1959,
                virtual: false,
                name: 'Sport Recife',
                mediumname: 'Sport Recife PE',
                abbr: 'REC',
                iscountry: false,
              },
            },
            score: {
              home: 2,
              away: 2,
            },
            aggregate: null,
            periods: {
              p1: {
                home: 0,
                away: 1,
              },
            },
            penalty_shootout: null,
            status: {
              _doc: 'status',
              _id: 7,
              name: '2nd half',
            },
            periodlength: 45,
            numberofperiods: 2,
          },
          season: {
            _id: 12825,
            name: 'Brasileiro Serie A 2016',
            year: '2016',
            seasontype: '21',
            tournamentname: 'Brasileiro Serie A',
            roundbyround: true,
          },
          tournament: {
            _utid: 325,
            name: 'Brasileiro Serie A',
            roundbyround: true,
            seasontype: '21',
          },
          event: {
            _id: 269275332,
            _utid: 1959,
            type: 'goal',
            time: 80,
            injurytime: 0,
            disabled: 0,
            name: 'Goal',
            owngoal: false,
            penalty: false,
          },
          player: {
            _id: 84883,
            _utid: 1959,
            shirtnumber: 3,
            name: 'Ronaldo Alves',
            fullname: 'Alves, Ronaldo Luiz',
            position: {
              name: 'Defender',
            },
          },
        }, {
          _doc: 'card',
          _type: 'soccer:card:player_season_stats',
          _id: 1831004,
          _generated: 1480203452,
          _updated: 1480203452,
          _client_generated: 1480203459,
          phrase: 'Vinicius Araujo (Sport Recife) has received a yellow card from Joao Batista de Arruda.',
          stats: {
            yellow_cards: 4,
            yellowred_cards: 0,
            red_cards: 0,
          },
          match: {
            _id: 9212297,
            _dt: {
              _doc: 'time',
              time: '23:00',
              date: '26/11/16',
              tz: 'CET',
              tzoffset: 3600,
              uts: 1480197600,
            },
            _utid: 325,
            _sid: 1,
            roundname: {
              _doc: 'tableround',
              _id: 37,
              name: 37,
            },
            a2: 'br',
            teams: {
              home: {
                _doc: 'team',
                _id: 5328,
                uid: 1973,
                virtual: false,
                name: 'America MG',
                mediumname: 'America Mineiro MG',
                abbr: 'MIN',
                iscountry: false,
              },
              away: {
                _doc: 'team',
                _id: 987542,
                uid: 1959,
                virtual: false,
                name: 'Sport Recife',
                mediumname: 'Sport Recife PE',
                abbr: 'REC',
                iscountry: false,
              },
            },
            score: {
              home: 2,
              away: 1,
            },
            aggregate: null,
            periods: {
              p1: {
                home: 0,
                away: 1,
              },
            },
            penalty_shootout: null,
            status: {
              _doc: 'status',
              _id: 7,
              name: '2nd half',
            },
            periodlength: 45,
            numberofperiods: 2,
          },
          season: {
            _id: 12825,
            name: 'Brasileiro Serie A 2016',
            year: '2016',
            seasontype: '21',
            tournamentname: 'Brasileiro Serie A',
            roundbyround: true,
          },
          tournament: {
            _utid: 325,
            name: 'Brasileiro Serie A',
            roundbyround: true,
            seasontype: '21',
          },
          event: {
            _id: 269275262,
            _utid: 1959,
            type: 'card',
            time: 79,
            injurytime: 0,
            disabled: 0,
            name: 'Yellow card',
            card: 'yellow',
          },
          player: {
            _id: 329237,
            _utid: 1959,
            shirtnumber: 9,
            name: 'Araujo, Vinicius',
            fullname: 'Vasconcelos Araujo, Vinicius',
            position: {
              name: 'Forward',
            },
          },
        }, {
          _doc: 'card',
          _type: 'soccer:card:player_season_stats',
          _id: 1830972,
          _generated: 1480203404,
          _updated: 1480203428,
          _client_generated: 1480203409,
          phrase: 'Joao Vitor (Ponte Preta) has received a first yellow card.',
          stats: {
            yellow_cards: 12,
            yellowred_cards: 0,
            red_cards: 0,
          },
          match: {
            _id: 9212281,
            _dt: {
              _doc: 'time',
              time: '23:00',
              date: '26/11/16',
              tz: 'CET',
              tzoffset: 3600,
              uts: 1480197600,
            },
            _utid: 325,
            _sid: 1,
            roundname: {
              _doc: 'tableround',
              _id: 37,
              name: 37,
            },
            a2: 'br',
            teams: {
              home: {
                _doc: 'team',
                _id: 5903,
                uid: 1958,
                virtual: false,
                name: 'Botafogo RJ',
                mediumname: 'Botafogo RJ',
                abbr: 'BOT',
                iscountry: false,
              },
              away: {
                _doc: 'team',
                _id: 5332,
                uid: 1969,
                virtual: false,
                name: 'Ponte Preta',
                mediumname: 'Ponte Preta SP',
                abbr: 'PON',
                iscountry: false,
              },
            },
            score: {
              home: 1,
              away: 1,
            },
            aggregate: null,
            periods: {
              p1: {
                home: 1,
                away: 0,
              },
            },
            penalty_shootout: null,
            status: {
              _doc: 'status',
              _id: 7,
              name: '2nd half',
            },
            periodlength: 45,
            numberofperiods: 2,
          },
          season: {
            _id: 12825,
            name: 'Brasileiro Serie A 2016',
            year: '2016',
            seasontype: '21',
            tournamentname: 'Brasileiro Serie A',
            roundbyround: true,
          },
          tournament: {
            _utid: 325,
            name: 'Brasileiro Serie A',
            roundbyround: true,
            seasontype: '21',
          },
          event: {
            _id: 269275158,
            _utid: 1969,
            type: 'card',
            time: 78,
            injurytime: 0,
            disabled: 0,
            name: 'Yellow card',
            card: 'yellow',
          },
          player: {
            _id: 123135,
            _utid: 1969,
            shirtnumber: 5,
            name: 'Joao Vitor',
            fullname: 'Lima Gomes, Joao Vitor',
            position: {
              name: 'Midfielder',
            },
          },
        }, {
          _doc: 'card',
          _type: 'soccer:scheduled:possession',
          _id: 1830940,
          _generated: 1480203251,
          _updated: 1480203251,
          _client_generated: 1480203269,
          phrase: 'After 75 minutes of play',
          stats: {
            ball_possession: {
              home: 53,
              away: 47,
            },
            ball_safe: {
              home: 20,
              away: 19,
            },
            attack: {
              home: 23,
              away: 19,
            },
            dangerous_attack: {
              home: 10,
              away: 9,
            },
          },
          match: {
            _id: 9212297,
            _dt: {
              _doc: 'time',
              time: '23:00',
              date: '26/11/16',
              tz: 'CET',
              tzoffset: 3600,
              uts: 1480197600,
            },
            _utid: 325,
            _sid: 1,
            roundname: {
              _doc: 'tableround',
              _id: 37,
              name: 37,
            },
            a2: 'br',
            teams: {
              home: {
                _doc: 'team',
                _id: 5328,
                uid: 1973,
                virtual: false,
                name: 'America MG',
                mediumname: 'America Mineiro MG',
                abbr: 'MIN',
                iscountry: false,
              },
              away: {
                _doc: 'team',
                _id: 987542,
                uid: 1959,
                virtual: false,
                name: 'Sport Recife',
                mediumname: 'Sport Recife PE',
                abbr: 'REC',
                iscountry: false,
              },
            },
            score: {
              home: 2,
              away: 1,
            },
            aggregate: null,
            periods: {
              p1: {
                home: 0,
                away: 1,
              },
            },
            penalty_shootout: null,
            status: {
              _doc: 'status',
              _id: 7,
              name: '2nd half',
            },
            periodlength: 45,
            numberofperiods: 2,
          },
          season: {
            _id: 12825,
            name: 'Brasileiro Serie A 2016',
            year: '2016',
            seasontype: '21',
            tournamentname: 'Brasileiro Serie A',
            roundbyround: true,
          },
          tournament: {
            _utid: 325,
            name: 'Brasileiro Serie A',
            roundbyround: true,
            seasontype: '21',
          },
          event: {
            _id: null,
            type: 'mockevent',
            time: 75,
            injurytime: 0,
            disabled: false,
            name: 'Team Statistics',
          },
        }, {
          _doc: 'card',
          _type: 'soccer:scheduled:possession',
          _id: 1830908,
          _generated: 1480203251,
          _updated: 1480203251,
          _client_generated: 1480203254,
          phrase: 'After 75 minutes of play',
          stats: {
            ball_possession: {
              home: 54,
              away: 46,
            },
            ball_safe: {
              home: 17,
              away: 20,
            },
            attack: {
              home: 22,
              away: 18,
            },
            dangerous_attack: {
              home: 15,
              away: 8,
            },
          },
          match: {
            _id: 9212281,
            _dt: {
              _doc: 'time',
              time: '23:00',
              date: '26/11/16',
              tz: 'CET',
              tzoffset: 3600,
              uts: 1480197600,
            },
            _utid: 325,
            _sid: 1,
            roundname: {
              _doc: 'tableround',
              _id: 37,
              name: 37,
            },
            a2: 'br',
            teams: {
              home: {
                _doc: 'team',
                _id: 5903,
                uid: 1958,
                virtual: false,
                name: 'Botafogo RJ',
                mediumname: 'Botafogo RJ',
                abbr: 'BOT',
                iscountry: false,
              },
              away: {
                _doc: 'team',
                _id: 5332,
                uid: 1969,
                virtual: false,
                name: 'Ponte Preta',
                mediumname: 'Ponte Preta SP',
                abbr: 'PON',
                iscountry: false,
              },
            },
            score: {
              home: 1,
              away: 1,
            },
            aggregate: null,
            periods: {
              p1: {
                home: 1,
                away: 0,
              },
            },
            penalty_shootout: null,
            status: {
              _doc: 'status',
              _id: 7,
              name: '2nd half',
            },
            periodlength: 45,
            numberofperiods: 2,
          },
          season: {
            _id: 12825,
            name: 'Brasileiro Serie A 2016',
            year: '2016',
            seasontype: '21',
            tournamentname: 'Brasileiro Serie A',
            roundbyround: true,
          },
          tournament: {
            _utid: 325,
            name: 'Brasileiro Serie A',
            roundbyround: true,
            seasontype: '21',
          },
          event: {
            _id: null,
            type: 'mockevent',
            time: 75,
            injurytime: 0,
            disabled: false,
            name: 'Team Statistics',
          },
        }],
      },
    }],
  },
};
